### ISSUE TITLE
Can we add types for this lib

### ISSUE THREAD

**Issue by QuantumInformation** [nspragg/filehound#81]
Would be great for ts-node projects.

**Comment by nspragg** [comment]
I'm happy to accept a PR for this.

**Comment by koocieyu** [comment]
hi there! i want to get this out of the way and say that what i made is incomplete and probably not the best work you'll see because i'm not really familiar with Typescript.

[this](https://gist.github.com/koocieyu/986793b36c76ffcefcb365b5372f3190) is what i have for now. i plan on adding jsdoc and making some fixes before making a PR.

**Comment by nspragg** [comment]
Released in 1.17.1
